### ISSUE TITLE
3.0.1 > 3.1.0rc1 update failed - DB corrupted

### ISSUE THREAD

**Issue by g574** [openethereum/backport-3.1#71]
_Before filing a new issue, please **provide the following information**._

- **OpenEthereum version**: 3.1.0
- **Operating system**: Linux
- **Installation**: downloaded zip file
- **Fully synchronized**: no
- **Network**: ethereum 
- **Restarted**: yes

**Steps to reproduce:**
1. I have an ETH mainnet Openethereum node on 3.0.1.
2. I ran the DB upgrade tool (https://github.com/openethereum/3.1-db-upgrade-tool).
3. Started Openethereum 3.1RC1 (I got it from here: https://github.com/openethereum/openethereum/issues/11881)
4. Openethereum fails with the following message:
```
Loading config file from /app/openethereum/conf/config_eth.toml
2020-10-07 14:25:13 UTC Starting OpenEthereum/v3.1.0-rc1-stable-16542bd-20200929/x86_64-linux-gnu/rustc1.46.0
2020-10-07 14:25:13 UTC Keys path /data/parity/base/keys/ethereum
2020-10-07 14:25:13 UTC DB path /data/parity/db/ethereum/db/906a34e69aec8c0d
2020-10-07 14:25:13 UTC State DB configuration: archive +Trace
2020-10-07 14:25:13 UTC Operating mode: active
2020-10-07 14:25:14 UTC DB corrupted: Invalid argument: You have to open all column families. Column families not opened: col6, col5, col4, col3, col2, col1, col0, attempting repair
```
Note: it is running with archive + Trace.

**Expected result:**
OE should be running.

**Comment by adria0** [comment]
Could you send us the `config_eth.toml` (masking private information) please?

**Comment by g574** [comment]
```
[parity]
# No updates will be auto-installed
#auto_update = "none"
# Disables auto downloading of new releases. Not recommended.
#no_download = true
# Blockchain and settings will be stored in /data/parity/base.
base_path = "/data/parity/base"
# Parity databases will be stored in /data/parity/db.
db_path = "/data/parity/db"

[ui]
# You will need to unlock accounts manually if Wallet is disabled.
#disable = true

[network]
# Parity will sync by downloading latest state first. Node will be operational in couple minutes.
warp = false

[rpc]
# Only selected APIs will be exposed over this interface.
#apis = ["web3", "eth", "net", "traces"]

interface = ****

[websockets]
# UI won't work and WebSockets server will be not available.
disable = true

[ipc]
# Only selected APIs will be exposed over this interface.
#apis = ["web3", "eth", "net", "trace"]

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true

[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Keep all state trie data. No pruning.
pruning = "archive"
# Set total amount of discretionary memory to use for the entire system, overrides other cache and queue options.
cache_size = 8192

[snapshots]
# Disables automatic periodic snapshots.
#disable_periodic = true
```

**Comment by rakita** [comment]
This error happens on the unsuccessful opening of rocksdb [here](https://github.com/paritytech/parity-common/blob/bf0ba8434f16a3700d0b445f48effa50c0e14b1a/kvdb-rocksdb/src/lib.rs#L353). Basically this is calling on rocksdb lib to open db.

it could be maybe helpful to just try the procedure again because there is a [report](https://github.com/openethereum/openethereum/issues/11881#issuecomment-706855135) from a user that it was okay for them for archive+tracing node.

Additionally, there is tool [ldb ](https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool)(from rocksdb) that we can use to check what column families remained in DB. Here is [link](https://packages.debian.org/sid/rocksdb-tools#:~:text=persistent%20Key%2DValue%20Store%20for%20Flash%20and%20RAM%20Storage%20(tools)&text=RocksDB%20uses%20a%20Log%20Structured,written%20entirely%20in%20C%2B%2B.&text=It%20supports%20various%20compression%20algorithms,for%20production%20support%20and%20debugging.). If you can execute:
`ldb list_column_families /home/openethereum/.local/share/openethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/`

**Comment by g574** [comment]
Hi @rakita , thanks for the help. I tried the very same steps again and now it worked.

**Comment by rakita** [comment]
Glad to hear that worked out.
